import { Component, computed, input, output, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { AdminAccount } from '../../core/models';

@Component({
  selector: 'app-admin-accounts', imports: [FormsModule],
  template: `<section class="card"><div class="heading"><div><p>GESTIONARE CONTURI</p><h2>Conturi de tranzacționare</h2></div><strong>{{filtered().length}} conturi</strong></div><div class="admin-toolbar"><label class="search-field">Caută cont sau client<input [(ngModel)]="query" (ngModelChange)="page.set(0)" placeholder="Nume, e-mail sau număr cont"></label><label>Stare<select [(ngModel)]="status" (ngModelChange)="page.set(0)"><option value="ALL">Toate stările</option><option>Active</option><option>Suspended</option><option>Closed</option></select></label><label>Monedă<select [(ngModel)]="currency" (ngModelChange)="page.set(0)"><option value="ALL">Toate monedele</option>@for(item of currencies();track item){<option>{{item}}</option>}</select></label><button type="button" class="reset-filter" (click)="resetFilters()">Resetează</button></div><div class="table-wrap"><table><thead><tr><th>Client</th><th>Cont</th><th>Monedă</th><th>Stare</th><th>Acțiuni</th></tr></thead><tbody>@for(account of paged();track account.accountId){<tr><td>{{account.customerName}}<br><small>{{account.email}}</small></td><td>{{account.accountNumber}}</td><td>{{account.currency}}</td><td>{{account.status}}</td><td><button (click)="openDecision(account)">{{account.status==='Active'?'Suspendă':'Reactivează'}}</button></td></tr>}</tbody></table></div>@if(!filtered().length){<p class="empty">Nu există conturi pentru filtrele alese.</p>}@if(pages()>1){<div class="pagination"><button [disabled]="page()===0" (click)="page.set(page()-1)">‹ Anterior</button><span>Pagina {{page()+1}} din {{pages()}}</span><button [disabled]="page()+1>=pages()" (click)="page.set(page()+1)">Următor ›</button></div>}</section>@if(selected()){<div class="overlay"><section class="modal"><h2>{{nextStatus()==='Suspended'?'Suspendă':'Reactivează'}} contul</h2><p>{{selected()!.accountNumber}} · {{selected()!.customerName}}</p><label>Motiv obligatoriu<textarea [(ngModel)]="reason" placeholder="Explică decizia administrativă."></textarea></label><div><button class="secondary" (click)="selected.set(null)">Anulează</button><button [disabled]="reason.trim().length<3" (click)="confirm()">Confirmă</button></div></section></div>}`,
  styles: `.card{padding:26px;border-radius:14px;background:#fff;box-shadow:0 8px 26px #14213d12}.card>p{color:#08736f;font-size:11px;font-weight:800}.table-wrap{overflow:auto}table{width:100%;min-width:650px;border-collapse:collapse}th,td{padding:13px;text-align:left;border-bottom:1px solid #e7eef2}small,p{color:#637083}button{padding:9px 12px;border:0;border-radius:7px;background:#087c86;color:#fff;font-weight:700}.overlay{position:fixed;inset:0;z-index:30;display:grid;place-items:center;background:#09284b88}.modal{display:grid;gap:14px;width:min(420px,90vw);padding:25px;border-radius:14px;background:#fff}.modal h2{margin:0}.modal label{display:grid;gap:7px;font-weight:700}.modal textarea{min-height:90px;padding:10px;border:1px solid #ccdbe4;border-radius:8px;font:inherit}.modal div{display:flex;justify-content:flex-end;gap:9px}.secondary{background:#eaf1f5;color:#365466}`
})
export class AdminAccountsComponent {
  readonly accounts = input<AdminAccount[]>([]);
  readonly changed = output<{ id: number; status: string; reason: string }>();
  readonly selected = signal<AdminAccount | null>(null);
  reason = '';
  query=''; status='ALL'; currency='ALL'; page=signal(0); readonly size=10;
  currencies=computed(()=>[...new Set(this.accounts().map(item=>item.currency))].sort());
  filtered=computed(()=>{const q=this.query.toLowerCase().trim();return this.accounts().filter(item=>(this.status==='ALL'||item.status===this.status)&&(this.currency==='ALL'||item.currency===this.currency)&&(!q||`${item.customerName} ${item.email} ${item.accountNumber}`.toLowerCase().includes(q)));});
  pages(){return Math.max(1,Math.ceil(this.filtered().length/this.size));} paged(){return this.filtered().slice(this.page()*this.size,(this.page()+1)*this.size);} resetFilters(){this.query='';this.status='ALL';this.currency='ALL';this.page.set(0);}
  nextStatus() { return this.selected()?.status === 'Active' ? 'Suspended' : 'Active'; }
  openDecision(account: AdminAccount) { this.selected.set(account); this.reason = ''; }
  confirm() { const account = this.selected(); if (account) { this.changed.emit({ id: account.accountId, status: this.nextStatus(), reason: this.reason.trim() }); this.selected.set(null); } }
}
