USE BrokerageDB;
GO
IF OBJECT_ID('audit.UserSessionHistory','U') IS NULL
CREATE TABLE audit.UserSessionHistory(
 UserSessionHistoryId BIGINT IDENTITY PRIMARY KEY, ApiUserId UNIQUEIDENTIFIER NOT NULL,
 DeviceInfo VARCHAR(300) NULL, IpAddress VARCHAR(64) NULL, LoggedInAt DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
 FOREIGN KEY(ApiUserId) REFERENCES security.ApiUser(ApiUserId));
IF OBJECT_ID('audit.OrderActivityLog','U') IS NULL
CREATE TABLE audit.OrderActivityLog(
 OrderActivityLogId BIGINT IDENTITY PRIMARY KEY, OrderId BIGINT NULL, Activity VARCHAR(50) NOT NULL, Details VARCHAR(1000) NULL,
 ChangedBy VARCHAR(320) NOT NULL, ChangedAt DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME());
GO
